# Generated by Django 2.2.12 on 2020-06-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200605_1918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('text', 'list')},
        ),
    ]
